create table irasas
(
    unikalusnr    bigint generated by default as identity
        primary key,
    kategorija    varchar(255),
    papildomainfo varchar(255),
    suma          real
);


create table islaiduirasas
(
    atsiskaitymobudas varchar(255),
    datasulaiku       timestamp,
    unikalusnr        bigint not null
        primary key
        constraint fkdsvxir5tj7p64o9cjc6lm3vb1
            references irasas
);


create table pajamuirasas
(
    data            date,
    pozymisaribanka boolean,
    unikalusnr      bigint not null
        primary key
        constraint fk349g5e071thwrfdg6sx0bx5qk
            references irasas
);

